DECLARE
    IS_EMPLOYMENT_TYPE_EXISTS NUMBER;
    IS_POSITION_LEVEL_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_EMPLOYMENT_TYPE_EXISTS
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'VACANCY'
    AND CONSTRAINT_NAME = 'CHK_EMPLOYMENT_TYPE';

SELECT COUNT(1) INTO IS_POSITION_LEVEL_EXISTS
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'VACANCY'
    AND CONSTRAINT_NAME = 'CHK_POSITION_LEVEL';

IF IS_EMPLOYMENT_TYPE_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[ALTER TABLE VACANCY ADD CONSTRAINT CHK_EMPLOYMENT_TYPE CHECK (EMPLOYMENT_TYPE IN (
'FULL_TIME', 'PART_TIME', 'SELF_EMPLOYED', 'FREELANCE', 'CONTRACT'))]';
    DBMS_OUTPUT.PUT_LINE('Constraint CHK_EMPLOYMENT_TYPE exists.');
END IF;

IF IS_POSITION_LEVEL_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[ALTER TABLE VACANCY ADD CONSTRAINT CHK_POSITION_LEVEL CHECK (POSITION_LEVEL IN (
'TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD'))]';
    DBMS_OUTPUT.PUT_LINE('Constraint CHK_POSITION_LEVEL exists.');
END IF;

END;
/

