DECLARE
    IS_COLUMN_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_COLUMN_EXISTS
FROM ALL_TAB_COLUMNS
WHERE  TABLE_NAME = UPPER('VACANCY')
    AND COLUMN_NAME = UPPER('TOOL_AND_TECHNOLOGY');

IF IS_COLUMN_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[
    ALTER TABLE VACANCY
    ADD TOOL_AND_TECHNOLOGY VARCHAR2(250)
]';
END IF;

END;
/



