DECLARE
    IS_COLUMN_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_COLUMN_EXISTS
FROM ALL_TAB_COLUMNS
WHERE  TABLE_NAME = UPPER('USERS')
    AND COLUMN_NAME = UPPER('ROLE');

IF IS_COLUMN_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[
    ALTER TABLE USERS
    ADD ROLE VARCHAR2(60) NOT NULL
    CONSTRAINT chk_ROLE CHECK (ROLE IN ('USER', 'RESEARCHER', 'ADMIN'))
]';
END IF;

END;
/

