DECLARE
    IS_TABLE_EXISTS NUMBER;
    IS_SEQ_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_TABLE_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = UPPER('USERS')
    AND OBJECT_TYPE = UPPER('TABLE');

SELECT COUNT(1) INTO IS_SEQ_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = UPPER('SEQ_USERS')
    AND OBJECT_TYPE = UPPER('SEQUENCE');

IF IS_TABLE_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[
    CREATE TABLE USERS (
        ID NUMBER(12, 0) NOT NULL,
        FIRST_NAME VARCHAR2(60),
        LAST_NAME VARCHAR2(60),
        PASSWORD VARCHAR2(250) NOT NULL,
        EMAIL VARCHAR2(250) NOT NULL UNIQUE,
        CONSTRAINT USERS_ID_PK PRIMARY KEY (ID))
]';
END IF;

IF IS_SEQ_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[
    CREATE SEQUENCE SEQ_USERS MINVALUE 0 MAXVALUE 999999999999999999
    INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE
]';
END IF;

END;
/
