DECLARE
    IS_EMPLOYMENT_TYPE_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_EMPLOYMENT_TYPE_EXISTS
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'WORK_EXPERIENCE'
    AND CONSTRAINT_NAME = 'CHK_WE_EMPLOYMENT_TYPE';

IF IS_EMPLOYMENT_TYPE_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[ALTER TABLE WORK_EXPERIENCE ADD CONSTRAINT CHK_WE_EMPLOYMENT_TYPE CHECK (EMPLOYMENT_TYPE IN (
'FULL_TIME', 'PART_TIME', 'SELF_EMPLOYED', 'FREELANCE', 'CONTRACT'))]';
    DBMS_OUTPUT.PUT_LINE('Constraint CHK_WE_EMPLOYMENT_TYPE created.');
END IF;

END;
/

