DECLARE
    IS_EMPLOYMENT_TYPE_EXISTS NUMBER;
    IS_SALARY_EXISTS NUMBER;
    IS_POSITION_LEVEL_EXISTS NUMBER;
    IS_DESCRIPTION_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_EMPLOYMENT_TYPE_EXISTS
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = UPPER('VACANCY')
    AND COLUMN_NAME = UPPER('EMPLOYMENT_TYPE');

SELECT COUNT(1) INTO IS_SALARY_EXISTS
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = UPPER('VACANCY')
    AND COLUMN_NAME = UPPER('SALARY');

SELECT COUNT(1) INTO IS_POSITION_LEVEL_EXISTS
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = UPPER('VACANCY')
    AND COLUMN_NAME = UPPER('POSITION_LEVEL');

SELECT COUNT(1) INTO IS_DESCRIPTION_EXISTS
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = UPPER('VACANCY')
    AND COLUMN_NAME = UPPER('DESCRIPTION');

IF IS_EMPLOYMENT_TYPE_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[ALTER TABLE VACANCY ADD EMPLOYMENT_TYPE VARCHAR2(100)]';
END IF;

IF IS_SALARY_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[ALTER TABLE VACANCY ADD SALARY NUMBER(10)]';
END IF;

IF IS_POSITION_LEVEL_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[ALTER TABLE VACANCY ADD POSITION_LEVEL VARCHAR2(100)]';
END IF;

IF IS_DESCRIPTION_EXISTS = 1 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE VACANCY ADD NEW_DESCRIPTION CLOB]';
    EXECUTE IMMEDIATE q'[UPDATE VACANCY SET NEW_DESCRIPTION = DESCRIPTION]';
    EXECUTE IMMEDIATE q'[ALTER TABLE VACANCY DROP COLUMN DESCRIPTION]';
    EXECUTE IMMEDIATE q'[ALTER TABLE VACANCY RENAME COLUMN NEW_DESCRIPTION TO DESCRIPTION]';
END IF;

END;
/

