DECLARE
    IS_TRIGGER_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_TRIGGER_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = UPPER('USERS_UPDATED_ON_TRG')
    AND OBJECT_TYPE = UPPER('TRIGGER');

IF IS_TRIGGER_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[
    CREATE TRIGGER USERS_UPDATED_ON_TRG
        BEFORE UPDATE ON USERS
        FOR EACH ROW
        BEGIN
            :NEW.UPDATED_ON := SYSTIMESTAMP;
        END;
]';
END IF;

END;
/

