DECLARE
    IS_TABLE_EXISTS NUMBER;
    IS_SEQ_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_TABLE_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = UPPER('USERS_CATEGORY')
    AND OBJECT_TYPE = UPPER('TABLE');

SELECT COUNT(1) INTO IS_SEQ_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = UPPER('SEQ_USERS_CATEGORY')
    AND OBJECT_TYPE = UPPER('SEQUENCE');

IF IS_TABLE_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[
    CREATE TABLE USERS_CATEGORY (
        ID NUMBER(12, 0) NOT NULL,
        TITLE VARCHAR2(60),
        USERS_ID NUMBER(12, 0) NOT NULL,
        CONSTRAINT USERS_CATEGORY_ID_PK PRIMARY KEY (ID),
        CONSTRAINT FK_USERS_CATEGORY_ID FOREIGN KEY (USERS_ID) REFERENCES USERS(ID)
        ON DELETE CASCADE)
]';
END IF;

IF IS_SEQ_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[
    CREATE SEQUENCE SEQ_USERS_CATEGORY MINVALUE 0 MAXVALUE 999999999999999999
    INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE
]';
END IF;

END;
/
