DECLARE
    IS_TABLE_EXISTS NUMBER;
    IS_SEQ_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_TABLE_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = UPPER('WORK_EXPERIENCE')
    AND OBJECT_TYPE = UPPER('TABLE');

SELECT COUNT(1) INTO IS_SEQ_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = UPPER('SEQ_WORK_EXPERIENCE')
    AND OBJECT_TYPE = UPPER('SEQUENCE');

IF IS_TABLE_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[
    CREATE TABLE WORK_EXPERIENCE (
        WORK_EXPERIENCE_ID NUMBER(12, 0) NOT NULL,
        USERS_ID NUMBER(12, 0) NOT NULL,
        COMPANY_NAME VARCHAR2(250),
        POSITION_TITLE VARCHAR2(250),
        EMPLOYMENT_TYPE VARCHAR2(100),
        DESCRIPTION VARCHAR2(250),
        TOOL_AND_TECHNOLOGY VARCHAR2(250),
        COUNTRY VARCHAR2(150),
        CITY VARCHAR2(150),
        START_DATE TIMESTAMP,
        END_DATE TIMESTAMP,
        CREATED_ON TIMESTAMP DEFAULT SYSTIMESTAMP,
        UPDATED_ON TIMESTAMP,
        CONSTRAINT PK_WORK_EXPERIENCE_ID PRIMARY KEY (WORK_EXPERIENCE_ID),
        CONSTRAINT FK_USER_ID FOREIGN KEY (USERS_ID) REFERENCES USERS(ID)
        ON DELETE CASCADE)
]';
END IF;

IF IS_SEQ_EXISTS = 0 THEN
EXECUTE IMMEDIATE q'[
    CREATE SEQUENCE SEQ_WORK_EXPERIENCE MINVALUE 0 MAXVALUE 999999999999999999
    INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE
]';
END IF;

END;
/
