DECLARE
    IS_TABLE_EXISTS NUMBER;
    IS_TRIGGER_EXISTS NUMBER;
BEGIN

SELECT COUNT(1) INTO IS_TABLE_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = UPPER('WORK_EXPERIENCE')
    AND OBJECT_TYPE = UPPER('TABLE');

SELECT COUNT(1) INTO IS_TRIGGER_EXISTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME = UPPER('WORK_EXPERIENCE_UPDATED_ON_TRG')
    AND OBJECT_TYPE = UPPER('TRIGGER');

IF IS_TRIGGER_EXISTS = 0 AND IS_TABLE_EXISTS = 1 THEN
EXECUTE IMMEDIATE q'[
    CREATE TRIGGER WORK_EXPERIENCE_UPDATED_ON_TRG
        BEFORE UPDATE ON WORK_EXPERIENCE
        FOR EACH ROW
        BEGIN
            :NEW.UPDATED_ON := SYSTIMESTAMP;
        END;
]';
END IF;

END;
/

